image: gitpod/workspace-python-3.12

vscode:
  extensions:
    - amazonwebservices.aws-toolkit-vscode
    - ms-python.python
    - ms-toolsai.jupyter
    - donjayamanne.python-extension-pack
    - donjayamanne.python-environment-manager
