tasks:
  - name: python
    init: |
      sudo apt-get update && sudo apt-get install python3-pip python3-venv python3-dev build-essential libssl-dev libffi-dev -y
vscode:
  extensions:
    - amazonwebservices.aws-toolkit-vscode
    - ms-python.python
    - donjayamanne.python-extension-pack
    - donjayamanne.python-environment-manager
