image: gitpod/workspace-python-3.12

tasks:
    - name: Setup
      init: cp ./dev-env/bash_aliases ~/.bash_aliases

vscode:
  extensions:
    - amazonwebservices.aws-toolkit-vscode
    - ms-python.python
    - ms-toolsai.jupyter
    - donjayamanne.python-extension-pack
    - donjayamanne.python-environment-manager
