image: gitpod/workspace-python-3.12

tasks:
    - name: dev env setup
      init: |
        cp ./dev-env/bash_aliases ~/.bash_aliases
        source ~/.bashrc
    - name: Setup python3 venv
      init: |
        python3 -m venv .venv && source .venv/bin/activate
        python -m pip install --upgrade pip
        pip install -r requirements.txt
